[package]
name = "shared_state_cuncurrency"
version = "0.1.0"
authors = ["samuel-cavalcanti <scavalcanti111@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
